ARG BASE_IMAGE=alpine
ARG BASE_VERSION=latest
FROM $BASE_IMAGE:$BASE_VERSION

ARG BASE_IMAGE=alpine
ARG BASE_VERSION=latest
ARG IMAGE_NAME
ARG IMAGE_TAG

ENV BASE_IMAGE="$BASE_IMAGE"
ENV BASE_VERSION="$BASE_VERSION"
ENV IMAGE_NAME="$IMAGE_NAME"
ENV IMAGE_TAG="$IMAGE_TAG"

COPY hello.txt hello.sh  /
CMD ["/bin/sh", "/hello.sh"]
